# Generated by Django 4.2 on 2023-04-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_last_updated_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'comments'},
        ),
    ]
